### ISSUE TITLE
New activity type: car maintenance record

### ISSUE THREAD

**Issue by biozz** [biozz/notebase#61]
Here is how car maintenance records look right now:

```yaml
aliases: 
tags:
  - maintenance
car: "[[vw]]"
date: 2025-04-23
milage: 113000
shop: Шиномонтаж Биба и Боба
summary: замена колёс
cost: 1250р
parts: []
created: 2025-04-13T23:38:21
modified: 2025-05-01T22:26:44
```

We could use something like this to implement a summary page for a maintenance record.

As for the `parts` field, it can be something like this:

```yaml
parts:
  - name: Nokian XPDDXPDDDLD1000
    price: 5000 RUB
    amount: 4
```
